language: python
jobs:
  include:
    - python: 2.7
    - python: 3.5
    - python: 3.6
    - python: 3.7
    - python: 3.8
    - python: “3.9-dev”
    - python: pypy
    - python: pypy3
    - name: "Python 3.7 on macOS"
      os: osx
      osx_image: xcode11.2
      language: shell
      before_install:
        - python -m pip install --upgrade pip pytest
    - name: "Python 3.7 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.7.0
        - python -m pip install --upgrade pip pytest
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
install:
  - python setup.py install
script:
  - pytest
